import random
import sys, pygame
import game.breakout_objects as breakout_objects

""" All functions were written by Gabriel C. Ullmann, unless otherwise noted.
Class representing the Breakout game"""
class BreakoutGame():

    def __init__(self):
        self._observers = []

    """Links an observer to the game instance, allowing it to notify changes to the agent."""
    def attach(self, observer: breakout_objects.Observer) -> None:
        self._observers.append(observer)

    """Removes an observer from the game instance."""
    def detach(self,observer: breakout_objects.Observer) -> None:
        self._observers.remove(observer)

    """Notify the agent that changes happened in the game state."""
    def notify(self, event: breakout_objects.Event) -> None:
        for observer in self._observers:
            observer.update(event)

    """Initialize game objects, notify game start."""
    def init_game(self):
        self.score = 0  
        self.wall = None
        self.ball_xspeed = breakout_objects.BALL_XSPEED
        self.ball_yspeed = breakout_objects.BALL_YSPEED
        self.lives = breakout_objects.MAX_LIVES
        self.bat_speed = breakout_objects.BAT_XSPEED
        self.size = self.width, self.height = 640, 480
        self.gameScreen = None
        self.gameClock = None

        self.init_graphics()
        self.init_objects()
        event = breakout_objects.Event(self.score, self.lives, self.bat, self.ball)
        self.notify(event)

    """Initialize pygame display and framerate control."""
    def init_graphics(self):
        pygame.init()  
        self.gameScreen = pygame.display.set_mode(self.size)
        self.gameClock = pygame.time.Clock()
        pygame.mouse.set_visible(0) 

    """Create instances of the game objects: bat, ball and walls.
    
    Author: John Cheetham, 2009 
    """
    def init_objects(self):
        self.wall = breakout_objects.Wall()
        self.wall.build_wall(self.width)
        self.bat = breakout_objects.Bat()
        self.ball = breakout_objects.Ball()
        self.bat.rect = self.bat.rect.move((self.width / 2) - (self.bat.rect.right / 2), self.height - 20)
        self.ball.rect = self.ball.rect.move((self.width / 2) + random.randint(-200, 200), self.height / 2)

    """Check for inputs, collision, update object positions. 
    Executes every step. Notify changes to the game state.

    Arguments
    ---------
    comm : int
        Input generated by the agent, either 0 or 1 (move left or right)
    """
    def run_logic(self, comm):
        self.check_agent_commands(comm)
        self.check_quit_command() 
        self.check_collision()   
        self.check_game_over_condition()  
        self.update_ball_position()  
        self.check_ball_hit_wall()    
        event = breakout_objects.Event(self.score, self.lives, self.bat, self.ball)
        self.notify(event)

    """Check the inputs given by the agent and move the bat accordingly

    Author: John Cheetham, 2009 

    Arguments
    ---------
    comm : int
        Input generated by the agent, either 0 or 1 (move left or right)
    """
    def check_agent_commands(self, comm):
        if comm == 0:                        
            self.bat.rect = self.bat.rect.move(-self.bat_speed, 0)     
            if (self.bat.rect.left < 0):                           
                self.bat.rect.left = 0      
        if comm == 1:                    
            self.bat.rect = self.bat.rect.move(self.bat_speed, 0)
            if (self.bat.rect.right > self.width):                            
                self.bat.rect.right = self.width

    """Check collision between ball and bat. Offset > 0 means ball has hit RHS of bat.
    Vary angle of ball depending on where ball hits bat.   

    Author: John Cheetham, 2009  
    """                
    def check_collision(self):
        if self.ball.is_collided(self.bat.rect):
            self.ball_yspeed = -self.ball_yspeed                            
            offset = self.ball.rect.center[0] - self.bat.rect.center[0]                                             
            if offset > 0:
                if offset > 30:  
                    self.ball_xspeed = 7
                elif offset > 23:                 
                    self.ball_xspeed = 6
                elif offset > 17:
                    self.ball_xspeed = 5 
            else:  
                if offset < -30:                             
                    self.ball_xspeed = -7
                elif offset < -23:
                    self.ball_xspeed = -6
                elif self.ball_xspeed < -17:
                    self.ball_xspeed = -5                

    """If ball is below screen height, lose 1 life. Put a new ball into the game.
    Notify changes to the game state.

    Author: John Cheetham, 2009  
    """      
    def check_game_over_condition(self):
        if self.ball.rect.top > self.height:
            self.lives -= 1    
            self.ball_xspeed = breakout_objects.BALL_XSPEED
            self.ball_yspeed = breakout_objects.BALL_YSPEED            
            self.ball.rect.center = self.width / 2 + random.randint(-200, 200), self.height / 3  

        if self.lives == 0:    
            event = breakout_objects.Event(self.score, self.lives, self.bat, self.ball)
            self.notify(event)

    """Update ball position, make it bounce when it hits the edges of the screen. 

    Author: John Cheetham, 2009  
    """              
    def update_ball_position(self):
        if self.ball.rect.left < 0 or self.ball.rect.right > self.width:
            self.ball_xspeed = -self.ball_xspeed                         
        if self.ball.rect.top < 0:
            self.ball_yspeed = -self.ball_yspeed    

        if self.ball_xspeed < 0 and self.ball.rect.left < 0:
            self.ball_xspeed = -self.ball_xspeed                                
        if self.ball_xspeed > 0 and self.ball.rect.right > self.width:
            self.ball_xspeed = -self.ball_xspeed                               

    """Check if ball hit wall, break wall and increase score by 10 points.

    Author: John Cheetham, 2009  
    """ 
    def check_ball_hit_wall(self):
        index = self.ball.rect.collidelist(self.wall.brickrect)       
        if index != -1: 
            if self.ball.rect.center[0] > self.wall.brickrect[index].right or \
                self.ball.rect.center[0] < self.wall.brickrect[index].left:
                self.ball_xspeed = -self.ball_xspeed
            else:
                self.ball_yspeed = -self.ball_yspeed                         
            self.wall.brickrect[index:index + 1] = []
            self.score += 10
        
    """Draw all game objects: ball, bat, wall bricks and score value

    Author: John Cheetham, 2009  
    """ 
    def render(self):
        self.gameClock.tick(60)

        self.gameScreen.fill(breakout_objects.BG_COLOR)
        scoretext, scoretextrect = breakout_objects.draw_text(self.score, self.width)
        self.gameScreen.blit(scoretext, scoretextrect)

        for i in range(0, len(self.wall.brickrect)):
            self.gameScreen.blit(self.wall.brick, self.wall.brickrect[i])    

        # if wall completely gone, rebuild it
        if self.wall.brickrect == []:              
            self.wall.build_wall(self.width)                
            self.ball_xspeed = breakout_objects.BALL_XSPEED
            self.ball_yspeed = breakout_objects.BALL_YSPEED              
            self.ball.rect.center = self.width / 2, self.height / 3
        
        self.gameScreen.blit(self.ball.sprite, self.ball.rect)
        self.gameScreen.blit(self.bat.sprite, self.bat.rect)
        pygame.display.flip()

    """Check if ESC or the close button are being pressed to quit the game.
    This will never be called explicitly by the agent, it depends on human interaction.

    Author: John Cheetham, 2009  
    """ 
    def check_quit_command(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    sys.exit()



        



